[package]
name = "rafael/framework"
version = "0.1.0"
license = "MIT"
authors = ["Rafael"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
sift = "csqrl/sift@0.0.11"
replica = "aykut92/replica@0.1.7"